keys:
  # You can get your age public key by running: age-keygen -y /path/to/key.txt
  - &netcup age1e2hh3n7fmx3sfgflxgscerfym7eqsn9gc4kq3fqwsq5cx5n7g90s9ld2v2
  - &macbook age1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklm  # replace with actual key

creation_rules:
  # Global secrets accessible by all systems
  - path_regex: hosts/secrets\.yaml$
    key_groups:
      - age:
          - *netcup
          - *macbook

  # Per-host secrets
  - path_regex: hosts/netcup/secrets\.yaml$
    key_groups:
      - age:
          - *netcup

  - path_regex: hosts/macbook-work/secrets\.yaml$
    key_groups:
      - age:
          - *macbook
